/**
 * Forum Engine API
 * Forum Engine API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ForumUser {
    /**
     * ID of the user
     */
    id?: string;

    /**
     * First Name of the User
     */
    firstName?: string;

    /**
     * Last Name of the User
     */
    lastName?: string;

    /**
     * Username of the User
     */
    userName?: string;

    /**
     * Password
     */
    password?: string;

    /**
     * E-mail do usuario
     */
    email?: string;

    /**
     * User status
     */
    status?: ForumUser.StatusEnum;

    /**
     * Where this user came from?
     */
    source?: ForumUser.SourceEnum;

    numMessages?: number;

    /**
     * Signature of the user
     */
    signature?: string;

    /**
     * When user was created
     */
    createdAt?: string;

    /**
     * When user was updated
     */
    updatedAt?: string;

}
export namespace ForumUser {
    export enum StatusEnum {
        ACTIVE = <any> 'ACTIVE',
        INACTIVE = <any> 'INACTIVE'
    }
    export enum SourceEnum {
        FORUM = <any> 'FORUM',
        FACEBOOK = <any> 'FACEBOOK',
        GOOGLE = <any> 'GOOGLE'
    }
}
